name: PyQGis Regression

on: push

jobs:
  pyqgis:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Change Brew Tap
        run: brew tap https://github.com/tillhainbach/macos-pyqgis-regression-test

      - name: Install QGIS
        run: brew install --cask Casks/qgis-ltr-3.16
      
      - name: Test PyQGIS
        run: bash qgis_test_script.sh LTR-3.16